# for generating dataset
name: h1of_fx
dag:
  enva:
    config:
      _target_: diffsynth.modules.envelope.ADSREnvelope
      max_value: 1.0
      channels: 1
    connections:
      floor: AMP_FLOOR
      peak: PEAK_A
      attack: AT_A
      decay: DE_A
      sus_level: SU_A
      release: RE_A
      note_off: NOTE_OFF
      noise_mag: NOISE_A
  envc:
    config:
      _target_: diffsynth.modules.envelope.ADSREnvelope
      channels: 1
    connections:
      floor: CUT_FLOOR
      peak: PEAK_C
      attack: AT_C
      decay: DE_C
      sus_level: SU_C
      release: RE_C
      note_off: NOTE_OFF
      noise_mag: NOISE_C
  harmor:
    config:
      _target_: diffsynth.modules.harmor.Harmor
      sample_rate: ${sample_rate}
      sep_amp: true
      n_oscs: 1
    connections:
      amplitudes: enva
      osc_mix: M_OSC
      f0_hz: BFRQ
      f0_mult: MULT
      cutoff: envc
      q: Q_FILT
  lfomd:
    config:
      _target_: diffsynth.modules.lfo.LFO
      channels: 1
      rate_range: [0.1, 10.0]
      frame_rate: 60
      sample_rate: ${sample_rate}
    connections:
      rate: LFO_RATE
      level: LFO_LEVEL
  moddelay:
    config:
      _target_: diffsynth.modules.delay.ModulatedDelay
      sample_rate: ${sample_rate}
    connections:
      audio: harmor
      delay_ms: MD_DELAY
      phase: lfomd
      depth: MD_DEPTH
      mix: MD_MIX
  reverb:
    config:
      _target_: diffsynth.modules.reverb.DecayReverb
      ir_length: 16000
    connections:
      audio: moddelay
      gain: REV_GAIN
      decay: REV_DEC
fixed_params: 
  AMP_FLOOR: 0
  NOISE_A: 0
  NOISE_C: 0
  NOTE_OFF: 0.75
  MD_DEPTH: 0.25
  LFO_RATE: 1.0
  LFO_LEVEL: 1.0
static_params: [BFRQ, M_OSC, MULT, Q_FILT, NOISE_C, NOISE_A, AT_A, DE_A, SU_A, RE_A, AMP_FLOOR, PEAK_A, AT_C, DE_C, SU_C, RE_C, CUT_FLOOR, PEAK_C, MD_DELAY, MD_DEPTH, MD_MIX, REV_GAIN, REV_DEC]
save_params: [harmor_amplitudes, harmor_osc_mix, harmor_f0_hz, harmor_f0_mult, harmor_cutoff, harmor_q, moddelay_delay_ms, moddelay_mix, moddelay_phase, reverb_gain, reverb_decay]