name: decoupled
dag:
  harmor:
    config:
      _target_: diffsynth.modules.harmor.HarmorDecoupled
      sample_rate: ${sample_rate}
      sep_amp: true
      n_oscs: 2
    connections:
      amplitudes: AMP
      osc_mix: M_OSC
      f0_hz: BFRQS
      cutoff: CUTOFF
      q: Q_FILT
fixed_params:
static_params: [BFRQS, M_OSC, MULT, Q_FILT]